// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqdjxwaifmxstibegxcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxZGp4d2FpZm14c3RpYmVneGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDIyNzgsImV4cCI6MjA3MzExODI3OH0.5Z1FZNpa7beL05kfzMBAMWrFNR7VgKcWWWbFuMJ7T_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});